version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"
            MYSQL_PASSWORD: "${DB_PW}"
        ports:
            - "3306:3306"